version: "3.1"

networks:
  flat-network:
    driver: bridge

services:
# BACKEND SERVICES CONTAINER #############################
  db:
    image: postgres
    restart: unless-stopped
    container_name: network_db
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    expose:
      - "5432"
    networks:
      - flat-network

  redis:
    image: redis:3.0
    networks:
      - flat-network

  server:
    restart: always
    build: .
    container_name: network_server
    env_file: .env
    volumes:
      - ./network_server:/code
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=network_db
      - "DB_POST=${DB_PORT}"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - flat-network

  nginx:
    image: nginx:1.17
    container_name: nginx
    env_file: .env
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .nginx:/etc/nginx/conf.d
      - "${LOG_PATH}:/var/log/nginx"
    depends_on:
      - server
    networks:
      - flat-network

volumes:
  data: