# Generated by Django 3.0 on 2020-11-09 15:50

import ckeditor.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import json.encoder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('device', models.CharField(max_length=100, null=True)),
                ('player_id', models.CharField(max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=json.encoder.JSONEncoder, help_text='Data send with notification', null=True, verbose_name='Payload')),
            ],
            options={
                'verbose_name': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('turn_off_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('image_field_name', models.TextField(blank=True, default=None, null=True, verbose_name='Image display field')),
                ('icon_field_name', models.TextField(blank=True, default=None, null=True, verbose_name='Icon display field')),
                ('accent_color', models.CharField(blank=True, default=None, help_text='Sets the circle color around your small icon that shows to the left of your notification text. Uses ARGB Hex value (E.g. FF9900FF).', max_length=8, null=True, verbose_name='Accent color')),
                ('launch_url_format', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Launch url format')),
                ('app_url_format', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='App url format')),
                ('sound', models.CharField(blank=True, default=None, help_text="The sound that plays when this notification is received by the device. If no sound is specified, the device's default sound will play.", max_length=50, null=True, verbose_name='sound')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplateLocalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Tiếng Việt')], default='vi', max_length=2, verbose_name='Language')),
                ('title_html', ckeditor.fields.RichTextField(default=None, verbose_name='Title format html')),
                ('title_plantext', models.TextField(default=None, verbose_name='Title format text')),
                ('content_html', ckeditor.fields.RichTextField(default=None, verbose_name='Content format html')),
                ('content_plantext', models.TextField(default=None, verbose_name='Content format text')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to='api.Notification')),
            ],
        ),
    ]
