# Generated by Django 3.0 on 2020-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201111_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Send the message to the client'),
        ),
    ]
