# Generated by Django 3.0 on 2020-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_system',
            field=models.BooleanField(default=True),
        ),
    ]
