# Generated by Django 3.0 on 2020-11-13 17:34

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import vjit_network.common.validators
import vjit_network.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='raw',
            field=models.FileField(help_text='The original file is uploaded from the client', max_length=500, storage=django.core.files.storage.FileSystemStorage(location='D://mediafiles'), upload_to=vjit_network.core.models.File.raw_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.doc', '.docx', '.ppt', '.pptx', '.pdf', '.avi', '.flv', '.mkv', '.mp4', '.wmv', '.vob', '.jpg', '.jpeg', '.gif', '.png', '.tiff', '.bmp']), vjit_network.common.validators.FileMaxSizeValidator(max_size=10485760)], verbose_name='File raw'),
        ),
    ]
