# Generated by Django 3.0 on 2020-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201115_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline'),
        ),
    ]
