# Generated by Django 3.0 on 2020-12-27 11:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'Others': '', 'argsEmail': [''], 'argsPhone': ['']}, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
