# Generated by Django 3.0 on 2020-12-27 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import json.encoder
import vjit_network.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201227_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=vjit_network.core.models.Student.default_student_extra, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
